# Simulator defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

# Source files
VERILOG_SOURCES += $(PWD)/cdc_snapshot.v

# Top level module name
TOPLEVEL = cdc_snapshot

# Python test module name
MODULE = test_cdc_snapshot

# Cocotb include
include $(shell cocotb-config --makefiles)/Makefile.sim